# Pytorch fundamentals

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.0.0


In [7]:
# Scalar

scalar = torch.tensor(345)
scalar

tensor(345)

In [17]:
tensor_1 = torch.empty(size = (1,3,3))
tensor_1
tensor_2 = torch.empty(size = (2,3))
tensor_2

tensor([[0.0000e+00, 1.0102e-38, 1.8754e+28],
        [4.1586e-05, 2.1764e-04, 1.3028e-11]])

#### If you have a numpy array and want to avoid a copy, use torch.as_tensor().?

torch.as_tensor([[1,-1],[1,-1]])

In [8]:
scalar.ndim

0

In [9]:
# tensor back as python int
scalar.item() 

345

In [10]:
# vector 
vector = torch.tensor([3,4])
vector

tensor([3, 4])

In [11]:
vector.ndim

1

In [12]:
vector.shape

torch.Size([2])

In [13]:
# Matrix 
matrix = torch.tensor([[7,8],
                      [1,2]])
matrix

tensor([[7, 8],
        [1, 2]])

In [14]:
matrix.ndim 

2

In [15]:
matrix.item

<function Tensor.item>

In [16]:
matrix.shape 

torch.Size([2, 2])

In [17]:
matrix[:]

tensor([[7, 8],
        [1, 2]])

In [19]:
matrix[0][1]

tensor(8)

In [21]:
# Tensor 
Tensor = torch.tensor([[[1,2,3],
                       [3,6,9],
                       [2,4,5]]])
Tensor

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [22]:
Tensor.ndim

3

In [23]:
Tensor.shape

torch.Size([1, 3, 3])

In [2]:
#Random Tesnors 
random_tensors = torch.rand(3,4)
random_tensors

tensor([[0.5680, 0.2370, 0.9758, 0.3936],
        [0.3563, 0.3116, 0.3977, 0.2868],
        [0.3490, 0.5319, 0.2729, 0.5878]])

In [5]:
random_tensors = torch.rand(2,3,4)
random_tensors

tensor([[[0.7924, 0.5015, 0.6743, 0.8598],
         [0.9297, 0.7826, 0.8642, 0.2951],
         [0.8414, 0.6669, 0.5062, 0.1909]],

        [[0.2731, 0.7911, 0.7302, 0.5432],
         [0.1081, 0.7480, 0.0469, 0.2910],
         [0.8351, 0.5034, 0.8421, 0.8096]]])

In [8]:
# Create a random tensor with similar shape to an image tensor 
random_image_size_tensor = torch.rand(3,224,244)
random_image_size_tensor.shape

torch.Size([3, 224, 244])

In [11]:
# zeros and ones 
zero = torch.zeros(size=(3,4,2))
zero

tensor([[[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]]])

In [12]:
one = torch.ones(size=(3,4,2))
one

tensor([[[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]]])

In [13]:
one.dtype

torch.float32

In [15]:
random_tensors.dtype

torch.float32

In [25]:
# creating a ranage of tensors
range_tensors = torch.arange(start = 0,end = 100 , step = 5)
range_tensors.shape

torch.Size([20])

In [29]:
range_tensors

tensor([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85,
        90, 95])

In [28]:
# creating tensors like 
ten_zeros = torch.zeros_like(input = range_tensors)
ten_zeros.shape

torch.Size([20])

In [30]:
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [50]:
# Float 32 tensor 
float_32_tensor = torch.tensor([3.0,6.0,9.0],dtype = None ,
                              device = None, 
                              requires_grad = False)

In [51]:
print(float_32_tensor.dtype)
print(float_32_tensor.device)
print(float_32_tensor.requires_grad)
float_32_tensor

torch.float32
cpu
False


tensor([3., 6., 9.])

In [47]:
float_16_tensor = float_32_tensor.type(torch.float16)

In [48]:
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [5]:
int_32_tensor = torch.tensor([3,6,9] , dtype = torch.int64)
int_32_tensor
tensor = torch.tensor([3,6,10])

In [14]:
%%time 
value = 0
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]
value

CPU times: total: 0 ns
Wall time: 0 ns


tensor(145)

In [15]:
%%time 
torch.matmul(tensor,tensor)

CPU times: total: 0 ns
Wall time: 0 ns


tensor(145)

In [17]:
tensor_A = torch.tensor([[1,2],
                        [3,4],
                        [5,6]])
tensor_B = torch.tensor([[7,8],
                        [9,10],
                        [11,12]])




In [18]:
tensor_B.T

tensor([[ 7,  9, 11],
        [ 8, 10, 12]])

In [21]:
tensor_B.T.shape

torch.Size([2, 3])

In [25]:
# tensor_C = torch.mm(tensor_A,tensor_B)  -> error because of A shape = (3,2) and B shape = (3,2)

tensor_C = torch.mm(tensor_A,tensor_B.T)
tensor_C

tensor([[ 23,  29,  35],
        [ 53,  67,  81],
        [ 83, 105, 127]])

In [1]:
import torch
torch.cuda.is_available()

True

In [2]:
!nvidia-smi

Sat May 13 19:43:38 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 522.06       Driver Version: 522.06       CUDA Version: 11.8     |
|-------------------------------+----------------------+----------------------+
| GPU  Name            TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ... WDDM  | 00000000:01:00.0 Off |                  N/A |
| N/A   40C    P3    12W /  N/A |      0MiB /  4096MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [6]:
device = "cuda" if torch.cuda.is_available() else "cpu"

## Putting tensors(andd models) on the gpu 


In [3]:
tensor = torch.tensor([1,2,3])

In [4]:
print(tensor,tensor.device)

tensor([1, 2, 3]) cpu


In [7]:
# move tensore to gpu(if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

### Moving tensors back to cpu

In [9]:
# if tnesor is on gpu , cant tranform it to numpy 
tensor_on_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [10]:
# To fix the gpu tensor with numpy issu , we can first set it to the cpu
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3], dtype=int64)

In [11]:
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')